apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: celery-worker } }
  template:
    metadata:
      labels: { app: celery-worker }
    spec:
      containers:
        - name: worker
          image: IMAGE_PLACEHOLDER
          command: ["python", "run.py", "worker"]
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "4Gi"
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
