packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  zod:
    zod: ^3.23.8

  "@emotion/styled":
    "@emotion/styled": ^11.13.0

  "@emotion/react":
    "@emotion/react": ^11.13.3

  "@emotion/cache":
    "@emotion/cache": ^11.13.1

  "axios":
    "axios": "^1.7.7"

  "typescript":
    "typescript": "5.8.3"

