apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: api } }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: IMAGE_PLACEHOLDER
          command: ["python", "run.py", "backend"]
          ports: [{ containerPort: 8000 }]
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet: { path: /docs, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: app-config
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
