apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: worker } }
  template:
    metadata:
      labels: { app: worker }
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames: ["localhost"]
      containers:
        - name: worker
          image: IMAGE_PLACEHOLDER
          command: ["python", "run.py", "worker"]
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "3"
              memory: "4Gi"
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: app-config
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
