apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: app
spec:
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: app
spec:
  template:
    spec:
      containers:
        - name: worker
          imagePullPolicy: IfNotPresent
